//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Borrowed
    {
        public int BookId { get; set; }
        public int MemberId { get; set; }
        public System.DateTime BorrowedOn { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool Returned { get; set; }
        public System.DateTime ReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
