//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Book_Author = new HashSet<Book_Author>();
            this.Book_Borrowed = new HashSet<Book_Borrowed>();
        }
    
        public int BookId { get; set; }
        public string Name { get; set; }
        public string ISBN { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public int NumberOfCopies { get; set; }
    
        public virtual ICollection<Book_Author> Book_Author { get; set; }
        public virtual ICollection<Book_Borrowed> Book_Borrowed { get; set; }
    }
}
