//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Book_Borrowed = new HashSet<Book_Borrowed>();
            this.Member_MembershipPlan = new HashSet<Member_MembershipPlan>();
        }
    
        public int MemberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime JoiningDate { get; set; }
    
        public virtual ICollection<Book_Borrowed> Book_Borrowed { get; set; }
        public virtual ICollection<Member_MembershipPlan> Member_MembershipPlan { get; set; }
    }
}
