//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipPlan
    {
        public MembershipPlan()
        {
            this.Member_MembershipPlan = new HashSet<Member_MembershipPlan>();
        }
    
        public int MembershipPlanId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Fee { get; set; }
        public string DueDateLimit { get; set; }
        public string NumberOfBooks { get; set; }
    
        public virtual ICollection<Member_MembershipPlan> Member_MembershipPlan { get; set; }
    }
}
